CREATE TABLE ROL(
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    descripcion TEXT
);

CREATE TABLE UNIVERSIDAD(
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    foto VARCHAR NOT NULL
);

CREATE TABLE USUARIO(
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    genero VARCHAR(10) NOT NULL,
    foto VARCHAR NOT NULL,
    correo VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    rol_id INTEGER REFERENCES ROL(id) NOT NULL,
    universidad_id INTEGER REFERENCES UNIVERSIDAD(id)
);

CREATE TABLE EQUIPO(
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    deporte VARCHAR(20) NOT NULL,
    genero VARCHAR(10) NOT NULL,
    categoria VARCHAR(20),
    entrenador_id INTEGER REFERENCES USUARIO(id) NOT NULL,
    universidad_id INTEGER REFERENCES UNIVERSIDAD(id) NOT NULL
);
